<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>891fb173-a8cc-48bb-9b91-cedb0ad1f83e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OAuth" Version="2.3.11" />
  </ItemGroup>

</Project>
